/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package apresentacao;

import entidade.Cliente;
import java.util.Vector;
import javax.swing.JDesktopPane;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import negocio.NCliente;

/**
 *
 * @author diogo.leal
 */
public class FrmPesCliente extends javax.swing.JInternalFrame {

    
    JDesktopPane pnlPrincipal;
    /**
     * Creates new form FrmPesCliente
     */
    public FrmPesCliente() {
        initComponents();
    }

    public FrmPesCliente(JDesktopPane pnlPrincipal, String cpf) {
        this();
        this.pnlPrincipal = pnlPrincipal;
        carregarCliente(cpf);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblPesCliente = new javax.swing.JTable();
        btnSair = new javax.swing.JButton();

        tblPesCliente.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(tblPesCliente);

        btnSair.setText("Sair");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 433, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnSair, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnSair)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    private void carregarCliente(String cpf) {

        try {

            Vector<String> cabecalho = new Vector();
            cabecalho.add("Código");
            cabecalho.add("Nome");
            cabecalho.add("CPF");
            cabecalho.add("Endereco");

            NCliente negocio = new NCliente();
            Vector linhas = new Vector();

            Cliente cliente = new Cliente();
            cliente = negocio.consulta(cpf);

            Vector<String> detalhe = new Vector();

            detalhe.add(cliente.getU().getCodigo() + "");
            detalhe.add(cliente.getU().getNome() + "");
            detalhe.add(cliente.getU().getCpf() + "");
            detalhe.add(cliente.getU().getRua() + " - " + cliente.getU().getLote() + " - " + cliente.getU().getQuadra() + "");

            linhas.add(detalhe);

            tblPesCliente.setModel(new DefaultTableModel(linhas, cabecalho));

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSair;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblPesCliente;
    // End of variables declaration//GEN-END:variables
}
